# Reusable workflow to build the application. The following inputs are defined as the working
# parameters of a build process:
# - package-name: The name of the package or project to build
# - upload-artifacts: Defines whether to upload the artifacts to GitHub Pages

name: 'Workflow: Build'

on:
  workflow_call:
    inputs:
      package-name:
        description: 'The name of the package or project to build'
        required: true
        type: string
      upload-artifacts:
        description: 'True if upload the artifacts to GitHub Pages is required; otherwise, false'
        required: false
        default: false
        type: boolean

jobs:
  # Build the application and upload the artifacts to Guthub Pages
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      node-version: 20.x

    steps:
    - uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v4
      if: ${{ inputs.upload-artifacts }}

    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node-version }}

    - name: Build
      run: |
        npm install -g @angular/cli
        npm install
        ng build --base-href=/${{ inputs.package-name }}/

    - name: Fix permissions
      if: ${{ inputs.upload-artifacts }}
      run: |
        chmod -c -R +rX "dist/${{ inputs.package-name }}/browser/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Upload Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/${{ inputs.package-name }}/browser/
      if: ${{ inputs.upload-artifacts }}
