# The deployment workflow that is triggered on pushed and PR integration
name: Deployment

on:
  push:
    branches: [ "feature/actions" ]

permissions:
  pages: write
  id-token: write

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/build.yml
    with:
      package-name: harpagon
      upload-artifacts: true

  cd:
    name: CD
    uses: ./.github/workflows/deploy.yml
    needs: ci

